name: adv_data_analytics
channels:
  - huggingface
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - jupyterlab=3.2.9
  - gensim=4.1.2
  - scikit-learn=1.0.2
  - datasets=1.18.3
  - ipywidgets=7.6.5
  - nltk=3.6.
  - pytorch=1.10.2
  - scipy=1.7.3
  - transformers=4.14.1
  - matplotlib
